### ISSUE TITLE
Bot randomly stops working

### ISSUE THREAD

**Issue by BluePigman** [BluePigman/BluePagmanBot#9]
![image](https://github.com/BluePigman/BluePagmanBot/assets/82780692/e0e25063-4829-473e-9e12-b47175bdb73c)
Sometimes just stops checking messages.

**Comment by BluePigman** [comment]
![image](https://github.com/BluePigman/BluePagmanBot/assets/82780692/2932e378-1815-4fb3-a475-47cba65b884b)
This doesn't fix the problem, because a socket.timeout seems to occur every minute. And also if we comment out the socket.timeout check, we still get
 Exception in loop_for_messages: The read operation timed out

**Comment by BluePigman** [comment]
Culprit: 16:11:34 Twitch Servers requested us to reconnect, reconnecting

**Comment by BluePigman** [comment]
The bot doesn't know how to reconnect.

**Comment by simulified** [comment]
There is a problem
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 1000; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```

**Comment by BluePigman** [comment]
Okay I think i found it: in chatterino, it shows the reconnect message, and I found the code which does that:
else if (command == "RECONNECT")
    {
        this->addGlobalSystemMessage(
            "Twitch Servers requested us to reconnect, reconnecting");
        this->markChannelsConnected();
        this->connect();
    }

**Comment by BluePigman** [comment]
Turns out RECONNECT is a twitch irc command, https://dev.twitch.tv/docs/irc/capabilities/

**Comment by BluePigman** [comment]
So let's try sending this command so the bot can receieve specific twitch IRC commands:
'CAP REQ :twitch.tv/membership twitch.tv/tags twitch.tv/commands'

**Comment by BluePigman** [comment]
Will also need to rewrite message parsing from scratch, as the new message has more information, also no need for api call to get user ids, as it is given in the new message as well.

**Comment by BluePigman** [comment]
Latest commit [3d82a10](https://github.com/BluePigman/BluePagmanBot/commit/3d82a10393b7cf1fe1c8d4713cd868014069daab) 
when twitch sends a reconnect notice message, bot will close connection and reconnect. Hopefully it works.

**Comment by BluePigman** [comment]
[7e2a660](https://github.com/BluePigman/BluePagmanBot/commit/7e2a660f1f0e60bdf4c1d34a8bbff42238d03433)
  Bot can receive RECONNECT command, just fixed a bug for sending messages to all channels instead of getting channel from the message, as there is no channel in the message.

**Comment by BluePigman** [comment]
Fixed
![image](https://github.com/user-attachments/assets/cc96cfd5-cae7-4f9f-b2ef-efdb9bc97217)
